version: "3.5"
services:
  gateway:
    container_name: exemple-gateway
    image: exemple-gateway
    networks:
    - authorization
    - service
    environment:
    - CATALINA_OPTS="-Dlogging.config=file:/usr/local/tomcat/etc/logback.groovy"
    - "JAVA_OPTS=-Xms256m -Xmx512m -XX:MetaspaceSize=128m"
    ports:
    - 8086:8080
    volumes:
    - ./docker/gateway:/usr/local/tomcat/etc
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "accept:application/json", "http://localhost:8080/actuator/health"]
      interval: 30s
      start_period: 30s
networks:
  authorization:
    external:
      name: exemple-authorization
  service:
    external:
      name: exemple-service