version: "3.5"
services:
  gateway:
    container_name: exemple-gateway
    image: exemple-gateway
    networks:
    - authorization
    - service
    environment:
    - "--spring.config.location=/usr/local/etc/gateway/exemple-gateway.yml"
    - "--server.servlet.context-path=/"
    - "JAVA_OPTS=-Xms256m -Xmx1g"
    - "JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
    ports:
    - 8086:8080
    - 9086:8000
    volumes:
    - ./docker/gateway:/usr/local/etc/gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "accept:application/json", "http://localhost:8080/actuator/health"]
      interval: 30s
      start_period: 30s
networks:
  authorization:
    external:
      name: exemple-authorization
  service:
    external:
      name: exemple-service